### ISSUE TITLE
Doesn't work on 2nd monitor

### ISSUE THREAD

**Issue by johnsonjo4531** [dfrankland/hyperterm-transparent-bg#1]
Hey I really like your plugin. I just used it today on a second monitor. It seems to just black out the background when dragged to a second monitor. Thought I might bring this to your attention.

**Comment by dfrankland** [comment]
I literally was just to about to create this issue! 👍 Thank you for creating it.

**Comment by johnsonjo4531** [comment]
Hey no problem. I also noticed one other thing. It has to do with themes. I'll add it in a second.

**Comment by dfrankland** [comment]
This should be fixed with this commit: https://github.com/dfrankland/hyperterm-transparent-bg/commit/90a4a63a1f0823e48797f76ee13bb4870c6c259f
