### ISSUE TITLE
How to achieve 100% transparency ?

### ISSUE THREAD

**Issue by justUmen** [dfrankland/hyperterm-transparent-bg#10]
Is it possible to achieve 100% transparency ?  

Opacity is working for as low as 0.1, but "as you said" 0 is just no color.  

... why is that ?

**Comment by dfrankland** [comment]
Set `opacity` to `1`.

> The `opacity` CSS property specifies the level of transparency of an element, that is, the degree to which the content behind the element is visible.
>
> &mdash; <https://developer.mozilla.org/en-US/docs/Web/CSS/opacity>
