### ISSUE TITLE
Usage with themes

### ISSUE THREAD

**Issue by johnsonjo4531** [dfrankland/hyperterm-transparent-bg#2]
There were two problems I had initially when using this plugin with other themes. One was that the background color from a theme would go over top the transparent background and it would be opaque. This was fixed by reordering the plugins and restarting hyperterm. (I put the theme before the hyperterm-transparent-bg plugin)

The other problem I was wondering if it could be fixed is whether the header (the tab section at the top) background could be changed to match the theme (the previous config before extension). I'm guessing the current coloring (black) that I am getting is coming from background-color being set by the transparent-bg plugin.  The header could be targeted specifically with the header_header class, but that may not be good practice to change.

**Comment by dfrankland** [comment]
As far as the ordering of themes and this plugin, that should definitely be documented—I'll do that next.

The tabs at the top on the other hand I think are out of the scope of this project. Changing the style of them should be handled in another plugin. Inside that plugin you'd then change the opacity of the tabs to allow the background to show through.

**Comment by dfrankland** [comment]
Documentation about usage was added with this commit: https://github.com/dfrankland/hyperterm-transparent-bg/commit/24efe4554356cc846706e2969b29cd139d5b448b
