### ISSUE TITLE
Transparency built in now?

### ISSUE THREAD

**Issue by dialupdisaster** [dfrankland/hyperterm-transparent-bg#5]
Have you guys seen this:

https://github.com/electron/electron/pull/949

Might be a ton less resource intense vs `<video>`

**Comment by dfrankland** [comment]
Yes, I have. [That's why I put a warning on the `README.md`.](https://github.com/dfrankland/hyperterm-transparent-bg#wat-how-does-it-work)

The issue is that you can't apply effects to the background like blur. See here: https://github.com/electron/electron/pull/949#issuecomment-68003136
